const fileTreeExtended = require("./index");


module.exports = {
  transformDefaults: {
    BADGES: {
      style: "for-the-badge",
    },
    fileTreeExtended: {
      descriptions: {
        ".qodo": "Qodana is a static analysis tool that can be used to find bugs and improve code quality.",
        "node_modules": "This directory contains all the project's dependencies.",
        ".gitignore": "This file specifies which files and folders should be ignored by Git.",
        "CONTRIBUTING.md": "This file provides guidelines for contributing to the project.",
        "index.js": "This is the main entry point of the `fileTreeExtended` transform.",
        "LICENSE": "This file contains the project's license information.",
        "markdown-magic.config.js": "This is the configuration file for `markdown-magic`.",
        "package-lock.json": "This file is automatically generated for any operations where `npm` modifies either the `node_modules` tree, or `package.json`.",
        "package.json": "This file contains metadata about the project and its dependencies.",
        "README.md": "This file provides a general overview of the project.",
        "RULES_OF_CONDUCT.md": "This file outlines the rules of conduct for the project's community."
      }
    },
  },
  transforms: {
    SCRIPTS: require("markdown-magic-scripts"),
    BADGES: require("markdown-magic-transform-badges"),
    ACKNOWLEDGEMENTS: require("markdown-magic-transform-acknowledgements"),
    fileTreeExtended: require("./index"),
  },
}
